x-mongo-env: &mongo-env
  MONGO_HOST: mongo
  MONGO_PORT: 27017

services:
  fastapi:
    build: ../../backend
    ports:
      - 8000:8000
    entrypoint: >
      sh -c "python main.py"
    environment:
      FASTAPI_DEBUG: True
      <<: *mongo-env
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:6.0.4
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/productiondb --quiet
      interval: 5s
      timeout: 5s
      retries: 100
