from typing import List

from fastapi import Depends
from fastapi.routing import APIRoute

from api.dependencies import check_film_exists, check_review_exists
from api.v1 import bookmarks, ratings, reviews
from models.responses import BookmarkResponse, RatingResponse, ReviewResponse

routes = [
    APIRoute(
        path='/bookmarks',
        methods=['GET'],
        summary='View list of bookmarks',
        response_description='User bookmarks (movies saved for later)',
        endpoint=bookmarks.get_user_bookmarks,
        response_model=List[BookmarkResponse],
        response_model_by_alias=False,
        tags=['bookmarks'],
    ),
    APIRoute(
        path='/films/{film_id}/bookmarks',
        methods=['POST'],
        summary='Add a movie to bookmarks',
        response_description='User bookmarks (movies saved for later)',
        endpoint=bookmarks.bookmark_film,
        response_model=List[BookmarkResponse],
        response_model_by_alias=False,
        dependencies=[Depends(check_film_exists)],
        tags=['bookmarks'],
    ),
    APIRoute(
        path='/films/{film_id}/bookmarks',
        methods=['DELETE'],
        summary='Remove a movie from bookmarks',
        response_description='User bookmarks (movies saved for later)',
        endpoint=bookmarks.unbookmark_film,
        response_model=List[BookmarkResponse],
        response_model_by_alias=False,
        dependencies=[Depends(check_film_exists)],
        tags=['bookmarks'],
    ),
    APIRoute(
        path='/films/{film_id}/ratings',
        methods=['GET'],
        summary='View movie ratings',
        response_description='Movie ratings (likes, dislikes, and average rating)',
        endpoint=ratings.get_film_rating,
        response_model=RatingResponse,
        response_model_by_alias=False,
        tags=['film_rating'],
    ),
    APIRoute(
        path='/films/{film_id}/ratings',
        methods=['POST'],
        summary='Add a rating to a movie',
        response_description='Movie ratings (likes, dislikes, and average rating)',
        endpoint=ratings.rate_film,
        response_model=RatingResponse,
        response_model_by_alias=False,
        tags=['film_rating'],
    ),
    APIRoute(
        path='/films/{film_id}/ratings',
        methods=['DELETE'],
        summary='Remove a rating from a movie',
        response_description='Movie ratings (likes, dislikes, and average rating)',
        endpoint=ratings.unrate_film,
        response_model=RatingResponse,
        response_model_by_alias=False,
        tags=['film_rating'],
    ),
    APIRoute(
        path='/films/{film_id}/reviews',
        methods=['GET'],
        summary='View a list of reviews',
        response_description='List of movie reviews',
        endpoint=reviews.get_film_reviews,
        response_model=List[ReviewResponse],
        response_model_by_alias=False,
        tags=['reviews'],
    ),
    APIRoute(
        path='/films/{film_id}/reviews',
        methods=['POST'],
        summary='Add a review to a movie',
        response_description='Movie review',
        endpoint=reviews.create_film_review,
        response_model=ReviewResponse,
        response_model_by_alias=False,
        response_model_exclude_none=True,
        dependencies=[Depends(check_film_exists)],
        tags=['reviews'],
    ),
    APIRoute(
        path='/films/{film_id}/reviews/{review_id}',
        methods=['DELETE'],
        summary='Remove a review from a movie',
        response_description='Movie review',
        endpoint=reviews.delete_film_review,
        dependencies=[Depends(check_film_exists), Depends(check_review_exists)],
        tags=['reviews'],
    ),
    APIRoute(
        path='/films/{film_id}/reviews/{review_id}/ratings',
        methods=['GET'],
        summary='View review ratings',
        response_description='Review ratings (likes, dislikes, and average rating)',
        endpoint=ratings.get_review_rating,
        response_model=RatingResponse,
        response_model_by_alias=False,
        dependencies=[Depends(check_film_exists)],
        tags=['review_rating'],
    ),
    APIRoute(
        path='/films/{film_id}/reviews/{review_id}/ratings',
        methods=['POST'],
        summary='Add a rating to a review',
        response_description='Review ratings (likes, dislikes, and average rating)',
        endpoint=ratings.rate_review,
        response_model=RatingResponse,
        response_model_by_alias=False,
        dependencies=[Depends(check_film_exists)],
        tags=['review_rating'],
    ),
    APIRoute(
        path='/films/{film_id}/reviews/{review_id}/ratings',
        methods=['DELETE'],
        summary='Remove a rating from a review',
        response_description='Review ratings (likes, dislikes, and average rating)',
        endpoint=ratings.unrate_review,
        response_model=RatingResponse,
        response_model_by_alias=False,
        dependencies=[Depends(check_film_exists)],
        tags=['review_rating'],
    ),
]
